package com.rcb.stocks.repositories;

import java.util.List;
import java.util.UUID;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import com.rcb.stocks.entity.StockData;

@Repository
public interface StockDataRepository extends CrudRepository<StockData, UUID>{
	//This is custom method, generated by defaultly by repository
	List<StockData> findAllByStock(String stock);
}
